// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RangarangTestProjectDATA.DataLayer;

#nullable disable

namespace RangarangTestProjectDATA.Migrations
{
    [DbContext(typeof(TheDbContext))]
    partial class TheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Circulation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CopyCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<float>("CutMargin")
                        .HasColumnType("real");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCalculatePrice")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCheckFile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCmyk")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomCirculation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomPage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomSize")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCirculation")
                        .HasColumnType("int");

                    b.Property<float?>("MaxLength")
                        .HasColumnType("real");

                    b.Property<int?>("MaxPage")
                        .HasColumnType("int");

                    b.Property<float?>("MaxWidth")
                        .HasColumnType("real");

                    b.Property<int?>("MinCirculation")
                        .HasColumnType("int");

                    b.Property<float?>("MinLength")
                        .HasColumnType("real");

                    b.Property<int?>("MinPage")
                        .HasColumnType("int");

                    b.Property<float?>("MinWidth")
                        .HasColumnType("real");

                    b.Property<string>("PageCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrintMargin")
                        .HasColumnType("real");

                    b.Property<byte>("PrintSide")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<byte>("ProductType")
                        .HasColumnType("tinyint");

                    b.Property<int>("SheetDimensionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdtId")
                        .HasColumnType("int");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<byte?>("Side")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAdts");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdtPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProductAdtId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAdtTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductPriceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductAdtId");

                    b.HasIndex("ProductAdtTypeId");

                    b.HasIndex("ProductPriceId");

                    b.ToTable("ProductAdtPrices");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdtType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdtTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductAdtId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductAdtId");

                    b.ToTable("ProductAdtTypes");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductDeliver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte>("CalcType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("EndCirculation")
                        .HasColumnType("int");

                    b.Property<bool>("IsIncreased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<byte>("PrintSide")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StartCirculation")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDelivers");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductDeliverSize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductDeliverId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSizeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProductDeliverId");

                    b.HasIndex("ProductSizeId");

                    b.ToTable("ProductDeliverSizes");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCombinedMaterial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomCirculation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMaterials");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductMaterialAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductMaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductMaterialId");

                    b.ToTable("ProductMaterialAttributes");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Circulation")
                        .HasColumnType("int");

                    b.Property<int?>("CopyCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDoubleSided")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductMaterialAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ProductPrintKindId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSizeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductID");

                    b.HasIndex("ProductMaterialAttributeId");

                    b.HasIndex("ProductMaterialId");

                    b.HasIndex("ProductPrintKindId");

                    b.HasIndex("ProductSizeId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductPrintKind", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsJeld")
                        .HasColumnType("bit");

                    b.Property<int>("PrintKindId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrintKinds");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductSize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetCount")
                        .HasColumnType("int");

                    b.Property<int?>("SheetDimensionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.Token", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdt", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.Product", "Product")
                        .WithMany("Adts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdtPrice", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.ProductAdt", "ProductAdt")
                        .WithMany("Prices")
                        .HasForeignKey("ProductAdtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RangarangTestProjectDATA.Domain.ProductAdtType", "ProductAdtType")
                        .WithMany("Prices")
                        .HasForeignKey("ProductAdtTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RangarangTestProjectDATA.Domain.ProductPrice", "ProductPrice")
                        .WithMany()
                        .HasForeignKey("ProductPriceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductAdt");

                    b.Navigation("ProductAdtType");

                    b.Navigation("ProductPrice");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdtType", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.ProductAdt", "ProductAdt")
                        .WithMany("Types")
                        .HasForeignKey("ProductAdtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAdt");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductDeliver", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.Product", "Product")
                        .WithMany("Delivers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductDeliverSize", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.ProductDeliver", "ProductDeliver")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductDeliverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RangarangTestProjectDATA.Domain.ProductSize", "ProductSize")
                        .WithMany("DeliverSizes")
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductDeliver");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductMaterial", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.Product", "Product")
                        .WithMany("Materials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductMaterialAttribute", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.ProductMaterial", "ProductMaterial")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductMaterial");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductPrice", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.Product", null)
                        .WithMany("Prices")
                        .HasForeignKey("ProductID");

                    b.HasOne("RangarangTestProjectDATA.Domain.ProductMaterialAttribute", "ProductMaterialAttribute")
                        .WithMany("Prices")
                        .HasForeignKey("ProductMaterialAttributeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RangarangTestProjectDATA.Domain.ProductMaterial", "ProductMaterial")
                        .WithMany("Prices")
                        .HasForeignKey("ProductMaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RangarangTestProjectDATA.Domain.ProductPrintKind", "ProductPrintKind")
                        .WithMany("Prices")
                        .HasForeignKey("ProductPrintKindId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RangarangTestProjectDATA.Domain.ProductSize", "ProductSize")
                        .WithMany("Prices")
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductMaterial");

                    b.Navigation("ProductMaterialAttribute");

                    b.Navigation("ProductPrintKind");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductPrintKind", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.Product", "Product")
                        .WithMany("PrintKinds")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductSize", b =>
                {
                    b.HasOne("RangarangTestProjectDATA.Domain.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.Product", b =>
                {
                    b.Navigation("Adts");

                    b.Navigation("Delivers");

                    b.Navigation("Materials");

                    b.Navigation("Prices");

                    b.Navigation("PrintKinds");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdt", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductAdtType", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductDeliver", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductMaterial", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductMaterialAttribute", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductPrintKind", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("RangarangTestProjectDATA.Domain.ProductSize", b =>
                {
                    b.Navigation("DeliverSizes");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
